tomlCopy[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://clawlaw-dev.netlify.app/"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"